'use client'

import {FormEvent,useEffect,useMemo,useRef,useState} from 'react'
import {AlertTriangle,BarChart3,ChevronDown,Dice5,Edit3,FlaskConical,GlassWater,Heart,History,Home,Lightbulb,LogOut,Minus,Plus,Search,ShoppingCart,Sparkles,Trash2,Wine,X} from 'lucide-react'
import {supabase} from '@/lib/supabase'
import {COCKTAIL_CATALOG,CatalogCocktail} from '@/lib/cocktailCatalog'

type Bottle={id:string;ingredient:string;brand:string|null;bottle_size_ml:number;remaining_ml:number;low_at_ml:number;is_open:boolean;purchase_price:number|null;abv:number|null;barcode:string|null}
type Ingredient={ingredient:string;amount_ml:number}
type SavedCocktail={id:string;name:string;description:string|null;instructions:string|null;glass:string|null;garnish:string|null;image_url:string|null;is_favorite:boolean;ingredients:Ingredient[]}
type ViewCocktail={id:string;name:string;description:string;instructions:string|null;glass:string|null;garnish:string|null;image_url:string|null;is_favorite:boolean;ingredients:Ingredient[];saved:boolean;tags:string[]}
type Pour={id:string;cocktail_name:string;made_at:string}
type MissingRow={ingredient:string;needed:number;have:number;add_ml:number;brand:string;bottle_size_ml:number;price:string;abv:string;selected:boolean}
type Tab='home'|'inspire'|'drinks'|'bar'|'shop'|'stats'
type DrinkFilter='all'|'makeable'|'almost'|'favorites'

const ING=['Vodka','Gin','White rum','Dark rum','Spiced rum','Tequila','Bourbon','Whiskey','Scotch','Brandy','Cognac','Triple sec','Cointreau','Grand Marnier','Vermouth sweet','Vermouth dry','Campari','Aperol','Amaretto','Kahlúa','Baileys','Malibu','Jägermeister','Angostura bitters','Lemon juice','Lime juice','Orange juice','Pineapple juice','Cranberry juice','Grapefruit juice','Tomato juice','Sugar syrup','Grenadine','Cola','Soda water','Tonic water','Ginger beer','Ginger ale','Cream','Milk','Coffee','Espresso','Mint','Egg white','Prosecco','Coconut cream','Peach schnapps']
const EMPTY={ingredient:'',brand:'',bottle_size_ml:'700',remaining_ml:'700',low_at_ml:'150',purchase_price:'',abv:'',barcode:'',is_open:true}
const MOODS=[['all','Alt'],['refreshing','Friskt'],['strong','Sterkt'],['sweet','Søtt'],['sour','Syrlig'],['easy','Enkelt'],['classic','Klassikere'],['tropical','Tropisk']]

export default function Page(){
 const [bottles,setBottles]=useState<Bottle[]>([])
 const [saved,setSaved]=useState<SavedCocktail[]>([])
 const [pours,setPours]=useState<Pour[]>([])
 const [tab,setTab]=useState<Tab>('home')
 const [q,setQ]=useState('')
 const [msg,setMsg]=useState('')
 const [searchOpen,setSearchOpen]=useState(false)
 const [activeSuggestion,setActiveSuggestion]=useState(-1)
 const searchRef=useRef<HTMLDivElement|null>(null)
 const [drinkFilter,setDrinkFilter]=useState<DrinkFilter>('all')
 const [mood,setMood]=useState('all')
 const [detail,setDetail]=useState<ViewCocktail|null>(null)
 const [featured,setFeatured]=useState<ViewCocktail|null>(null)
 const [bOpen,setBOpen]=useState(false)
 const [cOpen,setCOpen]=useState(false)
 const [bf,setBf]=useState(EMPTY)
 const [custom,setCustom]=useState('')
 const [expanded,setExpanded]=useState<Record<string,boolean>>({})
 const [cn,setCn]=useState(''),[cd,setCd]=useState(''),[ci,setCi]=useState(''),[cg,setCg]=useState(''),[cglass,setCglass]=useState('')
 const [recipe,setRecipe]=useState<Ingredient[]>([{ingredient:'',amount_ml:40}])
 const [missingCocktail,setMissingCocktail]=useState<ViewCocktail|null>(null)
 const [missingRows,setMissingRows]=useState<MissingRow[]>([])
 const [editBottle,setEditBottle]=useState<Bottle|null>(null)
 const [editForm,setEditForm]=useState({remaining_ml:'',bottle_size_ml:'',low_at_ml:'',purchase_price:'',abv:'',brand:'',barcode:'',is_open:true})

 async function load(){
  const [{data:bd},{data:cdat},{data:pd}]=await Promise.all([
   supabase.from('bar_bottles').select('*').order('ingredient'),
   supabase.from('bar_cocktails').select('id,name,description,instructions,glass,garnish,image_url,is_favorite,bar_recipe_ingredients(ingredient,amount_ml)').order('name'),
   supabase.from('bar_pours').select('id,cocktail_name,made_at').order('made_at',{ascending:false}).limit(250)
  ])
  setBottles((bd||[]) as Bottle[])
  setSaved((cdat||[]).map((x:any)=>({...x,ingredients:x.bar_recipe_ingredients||[]})))
  setPours((pd||[]) as Pour[])
 }
 useEffect(()=>{load()},[])
 useEffect(()=>{const close=(e:MouseEvent)=>{if(searchRef.current&&!searchRef.current.contains(e.target as Node)){setSearchOpen(false);setActiveSuggestion(-1)}};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[])

 const totals=useMemo(()=>Object.fromEntries([...new Set(bottles.map(x=>x.ingredient))].map(i=>[i,bottles.filter(x=>x.ingredient===i).reduce((s,x)=>s+Number(x.remaining_ml),0)])),[bottles])
 const pricePerMl=useMemo(()=>Object.fromEntries([...new Set(bottles.map(x=>x.ingredient))].map(i=>{const x=bottles.filter(v=>v.ingredient===i&&v.purchase_price);return[i,x.length?x.reduce((s,z)=>s+Number(z.purchase_price)/Number(z.bottle_size_ml),0)/x.length:0]})),[bottles])
 const abvByIng=useMemo(()=>Object.fromEntries([...new Set(bottles.map(x=>x.ingredient))].map(i=>{const x=bottles.filter(v=>v.ingredient===i&&v.abv!==null);return[i,x.length?x.reduce((s,z)=>s+Number(z.abv),0)/x.length:0]})),[bottles])
 const savedMap=useMemo(()=>new Map(saved.map(x=>[x.name.toLowerCase(),x])),[saved])
 const library=useMemo<ViewCocktail[]>(()=>{
  const catalog=COCKTAIL_CATALOG.map(cat=>{const s=savedMap.get(cat.name.toLowerCase());return s?{id:s.id,name:s.name,description:s.description||cat.description,instructions:s.instructions||cat.instructions||null,glass:s.glass||cat.glass||null,garnish:s.garnish||cat.garnish||null,image_url:s.image_url,is_favorite:s.is_favorite,ingredients:s.ingredients,saved:true,tags:cat.tags||[]}:{id:`catalog:${cat.name}`,name:cat.name,description:cat.description,instructions:cat.instructions||null,glass:cat.glass||null,garnish:cat.garnish||null,image_url:null,is_favorite:false,ingredients:cat.ingredients,saved:false,tags:cat.tags||[]}}
  const extra=saved.filter(s=>!COCKTAIL_CATALOG.some(c=>c.name.toLowerCase()===s.name.toLowerCase())).map(s=>({id:s.id,name:s.name,description:s.description||'Egen cocktail',instructions:s.instructions,glass:s.glass,garnish:s.garnish,image_url:s.image_url,is_favorite:s.is_favorite,ingredients:s.ingredients,saved:true,tags:['custom']}))
  return [...catalog,...extra]
 },[saved,savedMap])

 const servings=(x:{ingredients:Ingredient[]})=>x.ingredients.length?Math.max(0,Math.min(...x.ingredients.map(i=>Math.floor((totals[i.ingredient]||0)/i.amount_ml)))):0
 const missing=(x:{ingredients:Ingredient[]})=>x.ingredients.filter(i=>(totals[i.ingredient]||0)<i.amount_ml).map(i=>({...i,missing_ml:Math.max(0,i.amount_ml-(totals[i.ingredient]||0))}))
 const missingCount=(x:{ingredients:Ingredient[]})=>missing(x).length
 const cost=(x:{ingredients:Ingredient[]})=>x.ingredients.reduce((s,i)=>s+(pricePerMl[i.ingredient]||0)*i.amount_ml,0)
 const drinkAbv=(x:{ingredients:Ingredient[]})=>{const vol=x.ingredients.reduce((s,i)=>s+i.amount_ml,0);return vol?x.ingredients.reduce((s,i)=>s+i.amount_ml*((abvByIng[i.ingredient]||0)/100),0)/vol*100:0}
 const makeable=useMemo(()=>library.filter(x=>servings(x)>0).sort((a,b)=>servings(b)-servings(a)),[library,totals])
 const almost=useMemo(()=>library.filter(x=>servings(x)===0&&missingCount(x)===1).sort((a,b)=>missing(a)[0].missing_ml-missing(b)[0].missing_ml),[library,totals])
 const openIngredients=useMemo(()=>new Set(bottles.filter(x=>x.is_open&&x.remaining_ml>0).map(x=>x.ingredient)),[bottles])
 const useOpen=useMemo(()=>library.filter(x=>x.ingredients.some(i=>openIngredients.has(i.ingredient))).sort((a,b)=>servings(b)-servings(a)).slice(0,8),[library,openIngredients,totals])
 const groups=useMemo(()=>{const m=new Map<string,Bottle[]>();bottles.forEach(x=>{const k=[x.ingredient,(x.brand||''),x.bottle_size_ml].join('|').toLowerCase();m.set(k,[...(m.get(k)||[]),x])});return [...m.entries()]},[bottles])
 const low=bottles.filter(x=>Number(x.remaining_ml)<=Number(x.low_at_ml))
 const lowByIngredient=useMemo(()=>{const m=new Map<string,Bottle[]>();low.forEach(x=>m.set(x.ingredient,[...(m.get(x.ingredient)||[]),x]));return [...m.entries()]},[low])
 const smartBuys=useMemo(()=>{const out:Record<string,number>={};for(const d of library){if(servings(d)>0)continue;const m=missing(d);if(m.length===1)out[m[0].ingredient]=(out[m[0].ingredient]||0)+1}return Object.entries(out).sort((a,b)=>b[1]-a[1]).slice(0,6)},[library,totals])
 const top=useMemo(()=>{const m:Record<string,number>={};pours.forEach(x=>m[x.cocktail_name]=(m[x.cocktail_name]||0)+1);return Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,6)},[pours])
 const flash=(s:string)=>{setMsg(s);setTimeout(()=>setMsg(''),2800)}

 const searchResults=useMemo(()=>{let list=library.filter(x=>!q.trim()||x.name.toLowerCase().includes(q.trim().toLowerCase())||x.ingredients.some(i=>i.ingredient.toLowerCase().includes(q.trim().toLowerCase())));if(drinkFilter==='makeable')list=list.filter(x=>servings(x)>0);if(drinkFilter==='almost')list=list.filter(x=>servings(x)===0&&missingCount(x)<=2);if(drinkFilter==='favorites')list=list.filter(x=>x.is_favorite);return list.sort((a,b)=>{const sa=servings(a),sb=servings(b);if(sa!==sb)return sb-sa;const ma=missingCount(a),mb=missingCount(b);if(ma!==mb)return ma-mb;return a.name.localeCompare(b.name)})},[library,q,drinkFilter,totals])
 const suggestions=useMemo(()=>q.trim()?library.filter(x=>x.name.toLowerCase().includes(q.trim().toLowerCase())).slice(0,8):[],[library,q])
 const moodResults=useMemo(()=>{let list=mood==='all'?library:library.filter(x=>x.tags.includes(mood));return list.sort((a,b)=>{const sa=servings(a),sb=servings(b);if(sa!==sb)return sb-sa;return missingCount(a)-missingCount(b)}).slice(0,12)},[library,mood,totals])

 function onSearchKeyDown(e:React.KeyboardEvent<HTMLInputElement>){if(e.key==='Escape'){setSearchOpen(false);setActiveSuggestion(-1);return}if((e.key==='ArrowDown'||e.key==='ArrowUp')&&suggestions.length){e.preventDefault();setSearchOpen(true);setActiveSuggestion(i=>e.key==='ArrowDown'?(i>=suggestions.length-1?0:i+1):(i<=0?suggestions.length-1:i-1));return}if(e.key==='Enter'&&activeSuggestion>=0){e.preventDefault();const x=suggestions[activeSuggestion];setQ(x.name);setSearchOpen(false);setActiveSuggestion(-1);setDetail(x)}}
 function pickRandom(pool:ViewCocktail[]){const p=pool.length?pool:library;if(!p.length)return;const x=p[Math.floor(Math.random()*p.length)];setFeatured(x);setDetail(x)}

 async function ensureSaved(x:ViewCocktail){if(x.saved&&!x.id.startsWith('catalog:'))return x.id;const cat=COCKTAIL_CATALOG.find(c=>c.name.toLowerCase()===x.name.toLowerCase());const{data,error}=await supabase.from('bar_cocktails').insert({name:x.name,description:x.description,instructions:x.instructions,glass:x.glass,garnish:x.garnish}).select('id').single();if(error||!data){flash(error?.message||'Kunne ikke lagre drinken');return null}const{error:e}=await supabase.from('bar_recipe_ingredients').insert(x.ingredients.map(i=>({...i,cocktail_id:data.id})));if(e){flash(e.message);return null}await load();return data.id as string}
 async function makeDrink(x:ViewCocktail){const id=await ensureSaved(x);if(!id)return;const{error}=await supabase.rpc('make_cocktail',{p_cocktail_id:id});if(error)return flash(error.message);setDetail(null);await load();flash(`${x.name} laget · beholdningen er oppdatert`)}
 async function toggleFavorite(x:ViewCocktail){const id=await ensureSaved(x);if(!id)return;const current=savedMap.get(x.name.toLowerCase())?.is_favorite||false;await supabase.from('bar_cocktails').update({is_favorite:!current}).eq('id',id);await load()}

 function openMissing(x:ViewCocktail){const rows=missing(x).map(i=>{const existing=bottles.find(b=>b.ingredient===i.ingredient);return {ingredient:i.ingredient,needed:i.amount_ml,have:totals[i.ingredient]||0,add_ml:existing?Math.max(Math.ceil(i.missing_ml),100):700,brand:existing?.brand||'',bottle_size_ml:existing?.bottle_size_ml||700,price:existing?.purchase_price?.toString()||'',abv:existing?.abv?.toString()||'',selected:true}});setDetail(null);setMissingCocktail(x);setMissingRows(rows)}
 async function addMissingIngredients(){const chosen=missingRows.filter(r=>r.selected&&r.add_ml>0);if(!chosen.length)return flash('Velg minst én ingrediens');const rows=chosen.map(r=>({ingredient:r.ingredient,brand:r.brand||null,bottle_size_ml:Math.max(r.bottle_size_ml,r.add_ml),remaining_ml:r.add_ml,low_at_ml:150,is_open:true,purchase_price:r.price?Number(r.price):null,abv:r.abv?Number(r.abv):null}));const{error}=await supabase.from('bar_bottles').insert(rows);if(error)return flash(error.message);const name=missingCocktail?.name;setMissingCocktail(null);setMissingRows([]);await load();flash(`${chosen.length} ingrediens${chosen.length===1?'':'er'} lagt til${name?` for ${name}`:''}`)}

 async function addBottle(e:FormEvent){e.preventDefault();const ing=bf.ingredient==='__other__'?custom.trim():bf.ingredient;if(!ing)return;const{error}=await supabase.from('bar_bottles').insert({ingredient:ing,brand:bf.brand||null,bottle_size_ml:+bf.bottle_size_ml,remaining_ml:+bf.remaining_ml,low_at_ml:+bf.low_at_ml,is_open:bf.is_open,purchase_price:bf.purchase_price?+bf.purchase_price:null,abv:bf.abv?+bf.abv:null,barcode:bf.barcode||null});if(error)return flash(error.message);setBf(EMPTY);setCustom('');setBOpen(false);await load();flash('Flasken er registrert')}
 async function adjust(x:Bottle,d:number){const v=Math.max(0,Math.min(+x.bottle_size_ml,+x.remaining_ml+d));await supabase.from('bar_bottles').update({remaining_ml:v,is_open:true}).eq('id',x.id);await load()}
 async function toggleOpen(x:Bottle){await supabase.from('bar_bottles').update({is_open:!x.is_open}).eq('id',x.id);await load()}
 async function delBottle(id:string){await supabase.from('bar_bottles').delete().eq('id',id);await load()}
 function openEdit(x:Bottle){setEditBottle(x);setEditForm({remaining_ml:String(x.remaining_ml),bottle_size_ml:String(x.bottle_size_ml),low_at_ml:String(x.low_at_ml),purchase_price:x.purchase_price?.toString()||'',abv:x.abv?.toString()||'',brand:x.brand||'',barcode:x.barcode||'',is_open:x.is_open})}
 async function saveEdit(e:FormEvent){e.preventDefault();if(!editBottle)return;const size=Number(editForm.bottle_size_ml),remaining=Number(editForm.remaining_ml);if(size<=0||remaining<0||remaining>size)return flash('Sjekk flaske- og restmengde');const{error}=await supabase.from('bar_bottles').update({brand:editForm.brand||null,bottle_size_ml:size,remaining_ml:remaining,low_at_ml:Math.max(0,Number(editForm.low_at_ml)),purchase_price:editForm.purchase_price?Number(editForm.purchase_price):null,abv:editForm.abv?Number(editForm.abv):null,barcode:editForm.barcode||null,is_open:editForm.is_open}).eq('id',editBottle.id);if(error)return flash(error.message);setEditBottle(null);await load();flash('Flasken er oppdatert')}
 async function addOwn(e:FormEvent){e.preventDefault();if(!cn||!recipe.some(x=>x.ingredient&&x.amount_ml>0))return;const{data,error}=await supabase.from('bar_cocktails').insert({name:cn,description:cd||null,instructions:ci||null,garnish:cg||null,glass:cglass||null}).select('id').single();if(error||!data)return flash(error?.message||'Kunne ikke lagre');await supabase.from('bar_recipe_ingredients').insert(recipe.filter(x=>x.ingredient&&x.amount_ml>0).map(x=>({...x,cocktail_id:data.id})));setCn('');setCd('');setCi('');setCg('');setCglass('');setRecipe([{ingredient:'',amount_ml:40}]);setCOpen(false);await load();flash('Cocktailen er lagret')}

 function DrinkCard({x,compact=false}:{x:ViewCocktail;compact?:boolean}){const n=servings(x),m=missing(x),kr=cost(x),pct=drinkAbv(x);return <article className={`drinkcard ${compact?'compact':''}`} onClick={()=>setDetail(x)}><div className="drinkart"><GlassWater/><span>{x.tags[0]||'cocktail'}</span></div><div className="drinkcontent"><div className="drinktitle"><div><h3>{x.name}</h3><p>{x.description}</p></div><button className={'heart '+(x.is_favorite?'on':'')} onClick={e=>{e.stopPropagation();toggleFavorite(x)}}><Heart/></button></div><div className="statusrow"><span className={n>0?'status makeable':m.length<=2?'status near':'status missing'}>{n>0?`${n} ${n===1?'drink':'drinker'} mulig`:m.length===1?'Mangler 1 ting':`Mangler ${m.length}`}</span>{pct>0&&<span className="meta">≈ {pct.toFixed(0)}% ABV</span>}{kr>0&&<span className="meta">≈ {kr.toFixed(0)} kr</span>}</div>{!compact&&<div className="ingredientchips">{x.ingredients.slice(0,5).map(i=><span className={(totals[i.ingredient]||0)>=i.amount_ml?'have':'need'} key={i.ingredient}>{i.ingredient}</span>)}{x.ingredients.length>5&&<span>+{x.ingredients.length-5}</span>}</div>}</div></article>}

 return <main>
  <header className="topbar"><button className="brand brandbutton" onClick={()=>setTab('home')}><div className="logo"><Wine/></div><div><b>MoBar</b><small>inventory intelligence</small></div></button><div className="topstats"><span><b>{makeable.length}</b> kan lages</span><span><b>{bottles.length}</b> flasker</span></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut/>Logg ut</button></header>
  <nav className="mainnav"><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}><Home/>Hjem</button><button className={tab==='inspire'?'active':''} onClick={()=>setTab('inspire')}><Lightbulb/>Inspirasjon</button><button className={tab==='drinks'?'active':''} onClick={()=>setTab('drinks')}><GlassWater/>Alle drinker</button><button className={tab==='bar'?'active':''} onClick={()=>setTab('bar')}><FlaskConical/>Min bar</button><button className={tab==='shop'?'active':''} onClick={()=>setTab('shop')}><ShoppingCart/>Handleliste</button><button className={tab==='stats'?'active':''} onClick={()=>setTab('stats')}><BarChart3/>Innsikt</button></nav>
  {msg&&<div className="notice">{msg}</div>}

  {tab==='home'&&<><section className="homehero"><div><p className="eyebrow">MOBAR INVENTORY INTELLIGENCE</p><h1>Hva har du lyst på?</h1><p className="lead">MoBar ser på faktisk mengde i flaskene dine og forteller hva du kan lage nå, hva du nesten kan lage og hva som er smartest å kjøpe.</p><div className="heroactions"><button className="primary" onClick={()=>{setTab('inspire');pickRandom(makeable)}}><Dice5/>Overrask meg</button><button className="secondarybtn" onClick={()=>{setDrinkFilter('makeable');setTab('drinks')}}><GlassWater/>Se det jeg kan lage</button><button className="secondarybtn" onClick={()=>setBOpen(true)}><Plus/>Legg til flaske</button></div></div><div className="heroinsight"><span>AKKURAT NÅ</span><strong>{makeable.length}</strong><p>cocktails kan lages med beholdningen din</p><div><b>{almost.length}</b> er bare én ingrediens unna</div></div></section><section className="content dashboard"><div className="metricgrid"><article><FlaskConical/><div><b>{Math.round(bottles.reduce((s,x)=>s+Number(x.remaining_ml),0)/100)/10} L</b><span>totalt igjen</span></div></article><article><GlassWater/><div><b>{makeable.length}</b><span>kan lages nå</span></div></article><article><Sparkles/><div><b>{almost.length}</b><span>nesten mulig</span></div></article><article><AlertTriangle/><div><b>{lowByIngredient.length}</b><span>bør fylles på</span></div></article></div><div className="sectionhead"><div><p className="eyebrow">KLAR TIL Å LAGES</p><h2>Du har alt du trenger</h2></div><button onClick={()=>{setDrinkFilter('makeable');setTab('drinks')}}>Se alle</button></div><div className="drinkgrid">{makeable.slice(0,6).map(x=><DrinkCard key={x.id} x={x}/>)}</div>{makeable.length===0&&<div className="empty"><h3>Ingen komplette treff ennå</h3><p>Legg inn noen flasker, så begynner MoBar å gjøre nytte for seg.</p><button className="primary" onClick={()=>setBOpen(true)}><Plus/>Legg til flaske</button></div>}<div className="twocol"><div><div className="sectionhead"><div><p className="eyebrow">NESTEN DER</p><h2>Én ting unna</h2></div></div><div className="stack">{almost.slice(0,5).map(x=><DrinkCard key={x.id} x={x} compact/>)}</div></div><div><div className="sectionhead"><div><p className="eyebrow">SMART HANDLELISTE</p><h2>Mest effekt per kjøp</h2></div></div><div className="smartbuylist">{smartBuys.slice(0,5).map(([i,n],idx)=><button key={i} onClick={()=>setTab('shop')}><span>#{idx+1}</span><div><b>{i}</b><small>låser opp {n} {n===1?'cocktail':'cocktails'}</small></div><Plus/></button>)}</div></div></div></section></>}

  {tab==='inspire'&&<section className="content inspirepage"><div className="pagehero"><p className="eyebrow">INSPIRASJON</p><h1>Jeg vet ikke hva jeg vil ha.</h1><p>Helt normalt. La beholdningen gjøre den tunge tenkingen.</p><button className="primary big" onClick={()=>pickRandom(makeable.length?makeable:library)}><Dice5/>Gi meg noe tilfeldig</button></div><div className="moodchips">{MOODS.map(([k,l])=><button className={mood===k?'active':''} key={k} onClick={()=>setMood(k)}>{l}</button>)}</div><div className="sectionhead"><div><p className="eyebrow">BASERT PÅ BAREN DIN</p><h2>{mood==='all'?'Forslag akkurat nå':`Humør: ${MOODS.find(x=>x[0]===mood)?.[1]}`}</h2></div></div><div className="drinkgrid">{moodResults.map(x=><DrinkCard key={x.id} x={x}/>)}</div>{useOpen.length>0&&<><div className="sectionhead spaced"><div><p className="eyebrow">BRUK DET SOM ER ÅPENT</p><h2>Drinker som passer åpne flasker</h2></div></div><div className="horizontalcards">{useOpen.map(x=><DrinkCard key={x.id} x={x} compact/>)}</div></>}</section>}

  {tab==='drinks'&&<section className="content drinkspage"><div className="pagehero small"><p className="eyebrow">COCKTAILKATALOG</p><h1>Alle drinker</h1><p>Søk på navn eller ingrediens. MoBar rangerer automatisk det du faktisk kan lage øverst.</p></div><div className="searchwrap" ref={searchRef}><div className="search bigsearch"><Search/><input role="combobox" aria-expanded={searchOpen&&suggestions.length>0} aria-controls="cocktail-suggestions" value={q} onFocus={()=>{if(q.trim())setSearchOpen(true)}} onChange={e=>{setQ(e.target.value);setSearchOpen(Boolean(e.target.value.trim()));setActiveSuggestion(-1)}} onKeyDown={onSearchKeyDown} placeholder="Søk Long Island, gin, tequila…" autoComplete="off"/>{q&&<button onClick={()=>{setQ('');setSearchOpen(false);setActiveSuggestion(-1)}}><X/></button>}</div>{searchOpen&&suggestions.length>0&&<div className="suggestions" id="cocktail-suggestions" role="listbox">{suggestions.map((x,i)=><button key={x.id} role="option" aria-selected={i===activeSuggestion} className={i===activeSuggestion?'activeSuggestion':''} onMouseEnter={()=>setActiveSuggestion(i)} onClick={()=>{setQ(x.name);setSearchOpen(false);setActiveSuggestion(-1);setDetail(x)}}><GlassWater/><span><b>{x.name}</b><small>{servings(x)>0?`${servings(x)} kan lages`:`Mangler ${missingCount(x)} ingrediens${missingCount(x)===1?'':'er'}`}</small></span><em>Åpne</em></button>)}</div>}</div><div className="filterbar"><button className={drinkFilter==='all'?'active':''} onClick={()=>setDrinkFilter('all')}>Alle <b>{library.length}</b></button><button className={drinkFilter==='makeable'?'active':''} onClick={()=>setDrinkFilter('makeable')}>Kan lages <b>{makeable.length}</b></button><button className={drinkFilter==='almost'?'active':''} onClick={()=>setDrinkFilter('almost')}>Nesten <b>{library.filter(x=>servings(x)===0&&missingCount(x)<=2).length}</b></button><button className={drinkFilter==='favorites'?'active':''} onClick={()=>setDrinkFilter('favorites')}>Favoritter <b>{library.filter(x=>x.is_favorite).length}</b></button><button className="rightaction" onClick={()=>setCOpen(true)}><Plus/>Egen cocktail</button></div><div className="resultsline"><span>{searchResults.length} treff</span><span>Sortert etter hva du kan lage</span></div><div className="drinkgrid">{searchResults.map(x=><DrinkCard key={x.id} x={x}/>)}</div></section>}

  {tab==='bar'&&<section className="content"><div className="pagehero small"><p className="eyebrow">BEHOLDNING</p><h1>Min bar</h1><p>{bottles.length} fysiske flasker · {groups.length} typer · {Math.round(bottles.reduce((s,x)=>s+Number(x.remaining_ml),0)/100)/10} liter registrert.</p><button className="primary" onClick={()=>setBOpen(true)}><Plus/>Ny flaske</button></div><div className="bottlegrid">{groups.map(([k,list])=>{const first=list[0],total=list.reduce((s,x)=>s+Number(x.remaining_ml),0),cap=list.length*Number(first.bottle_size_ml),open=expanded[k]||list.length===1;return <article className="bottle" key={k}><div className="bottlehead"><FlaskConical/><div><h3>{first.brand||first.ingredient}</h3><p>{first.ingredient} · {list.length} {list.length===1?'flaske':'flasker'}</p></div><button className="expandbtn" onClick={()=>setExpanded(v=>({...v,[k]:!open}))}><ChevronDown className={open?'rotated':''}/></button></div><div className="meter"><i style={{width:`${Math.round(total/cap*100)}%`}}/></div><div className="amount"><strong>{Math.round(total)} ml</strong><span>av {cap} ml</span></div>{open&&<div className="individuals">{[...list].sort((a,z)=>Number(z.is_open)-Number(a.is_open)).map((x,i)=><div className="individual individual-v2" key={x.id}><div><b>Flaske {i+1} · {x.is_open?'åpen':'uåpnet'}</b><span>{Math.round(+x.remaining_ml)} / {x.bottle_size_ml} ml{x.abv?` · ${x.abv}%`:''}{x.purchase_price?` · ${x.purchase_price} kr`:' · pris ikke satt'}</span></div>{+x.remaining_ml<=+x.low_at_ml&&<AlertTriangle className="warn"/>}<button onClick={()=>adjust(x,-10)}><Minus/></button><button onClick={()=>adjust(x,10)}><Plus/></button><button className="statebtn" onClick={()=>toggleOpen(x)}>{x.is_open?'Lukk':'Åpne'}</button><button className="editbtn" onClick={()=>openEdit(x)}><Edit3/></button><button className="iconbtn" onClick={()=>delBottle(x.id)}><Trash2/></button></div>)}</div>}</article>})}</div></section>}

  {tab==='shop'&&<section className="content"><div className="pagehero small"><p className="eyebrow">HANDLELISTE</p><h1>Kjøp det som gir mest mening</h1><p>MoBar ser både på lav beholdning og hvilke nye cocktails ett kjøp åpner.</p></div>{smartBuys.length>0&&<div className="unlockbox"><Sparkles/><div><b>Størst effekt akkurat nå</b>{smartBuys.map(([i,n])=><p key={i}><strong>{i}</strong> gir tilgang til {n} {n===1?'ny cocktail':'nye cocktails'}</p>)}</div></div>}<div className="sectionhead"><div><p className="eyebrow">LAV BEHOLDNING</p><h2>På tide å fylle på</h2></div></div><div className="shopping">{lowByIngredient.map(([ingredient,list])=>{const first=list[0],left=list.reduce((s,x)=>s+Number(x.remaining_ml),0);return <div key={ingredient}><AlertTriangle/><div><h3>{first.brand||ingredient}</h3><p>{ingredient} · {Math.round(left)} ml igjen totalt</p></div><strong>KJØP {first.bottle_size_ml} ML</strong></div>})}</div>{lowByIngredient.length===0&&<div className="empty"><h3>Ingenting haster</h3><p>Ingen ingredienser er under handlegrensen akkurat nå.</p></div>}</section>}

  {tab==='stats'&&<section className="content"><div className="pagehero small"><p className="eyebrow">INNSIKT</p><h1>Hva skjer egentlig i baren?</h1></div><div className="statsgrid"><article><History/><b>{pours.length}</b><span>drinker registrert</span></article><article><FlaskConical/><b>{Math.round(bottles.reduce((s,x)=>s+Number(x.remaining_ml),0)} ml</b><span>totalt på lager</span></article><article><GlassWater/><b>{makeable.length}</b><span>cocktails kan lages</span></article><article><Heart/><b>{library.filter(x=>x.is_favorite).length}</b><span>favoritter</span></article></div><div className="insightgrid"><div><h2>Mest laget</h2>{top.length?top.map(([name,n],i)=><p key={name}><span>#{i+1} {name}</span><strong>{n}</strong></p>):<p>Ingen historikk ennå.</p>}</div><div><h2>Siste serveringer</h2>{pours.slice(0,10).map(x=><p key={x.id}><span>{x.cocktail_name}</span><small>{new Date(x.made_at).toLocaleString('nb-NO')}</small></p>)}</div></div></section>}

  {detail&&<div className="modalback" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null)}}><div className="modal drinkdetail"><button className="close" onClick={()=>setDetail(null)}><X/></button><div className="detailhero"><div className="detailart"><GlassWater/></div><div><p className="eyebrow">{detail.saved?'I DIN SAMLING':'MOBAR-KATALOG'}</p><h2>{detail.name}</h2><p>{detail.description}</p><div className="statusrow"><span className={servings(detail)>0?'status makeable':missingCount(detail)<=2?'status near':'status missing'}>{servings(detail)>0?`${servings(detail)} ${servings(detail)===1?'drink':'drinker'} mulig`:`Mangler ${missingCount(detail)}`}</span>{drinkAbv(detail)>0&&<span className="meta">≈ {drinkAbv(detail).toFixed(0)}% ABV</span>}{cost(detail)>0&&<span className="meta">≈ {cost(detail).toFixed(0)} kr</span>}</div></div></div><div className="detailgrid"><div><h3>Ingredienser</h3><div className="ingredientlist">{detail.ingredients.map(i=>{const have=totals[i.ingredient]||0,ok=have>=i.amount_ml;return <div key={i.ingredient}><span className={ok?'dot ok':'dot'}/><div><b>{i.ingredient}</b><small>{ok?`${Math.round(have)} ml på lager`:`Har ${Math.round(have)} ml · mangler ${Math.ceil(i.amount_ml-have)} ml`}</small></div><strong>{i.amount_ml} ml</strong></div>})}</div></div><div><h3>Slik lager du den</h3>{detail.glass&&<p><b>Glass:</b> {detail.glass}</p>}{detail.garnish&&<p><b>Garnityr:</b> {detail.garnish}</p>}<p>{detail.instructions||'Bygg eller shake drinken etter ønsket metode og server kald.'}</p></div></div><div className="detailactions"><button className="secondarybtn" onClick={()=>toggleFavorite(detail)}><Heart/>Favoritt</button>{servings(detail)>0?<button className="primary" onClick={()=>makeDrink(detail)}><GlassWater/>Lag drinken · trekk fra lager</button>:<button className="primary" onClick={()=>openMissing(detail)}><Plus/>Legg til det som mangler</button>}</div></div></div>}

  {missingCocktail&&<div className="modalback"><div className="modal wide missingmodal"><button className="close" onClick={()=>setMissingCocktail(null)}><X/></button><p className="eyebrow">MANGLER TIL OPPSKRIFTEN</p><h2>{missingCocktail.name}</h2><p className="modalintro">Velg hva du vil legge til. Mengde, flaskestørrelse, merke, pris og ABV kan endres før lagring.</p><div className="missingrows">{missingRows.map((r,i)=><div className={'missingrow '+(r.selected?'selected':'')} key={r.ingredient}><label className="missingcheck"><input type="checkbox" checked={r.selected} onChange={e=>setMissingRows(v=>v.map((x,n)=>n===i?{...x,selected:e.target.checked}:x))}/><span><b>{r.ingredient}</b><small>Har {Math.round(r.have)} ml · trenger {r.needed} ml</small></span></label><div className="missingfields"><label>Legg til, ml<input type="number" min="1" value={r.add_ml} onChange={e=>setMissingRows(v=>v.map((x,n)=>n===i?{...x,add_ml:Number(e.target.value)}:x))}/></label><label>Flaskestørrelse<input type="number" min="1" value={r.bottle_size_ml} onChange={e=>setMissingRows(v=>v.map((x,n)=>n===i?{...x,bottle_size_ml:Number(e.target.value)}:x))}/></label><label>Merke<input value={r.brand} onChange={e=>setMissingRows(v=>v.map((x,n)=>n===i?{...x,brand:e.target.value}:x))}/></label><label>Pris, kr<input type="number" min="0" value={r.price} onChange={e=>setMissingRows(v=>v.map((x,n)=>n===i?{...x,price:e.target.value}:x))}/></label><label>ABV, %<input type="number" min="0" max="100" step="0.1" value={r.abv} onChange={e=>setMissingRows(v=>v.map((x,n)=>n===i?{...x,abv:e.target.value}:x))}/></label></div></div>)}</div><button className="savebtn" onClick={addMissingIngredients}>Legg valgte ingredienser i beholdningen</button></div></div>}

  {editBottle&&<div className="modalback"><form className="modal" onSubmit={saveEdit}><button type="button" className="close" onClick={()=>setEditBottle(null)}><X/></button><p className="eyebrow">REDIGER FLASKE</p><h2>{editBottle.brand||editBottle.ingredient}</h2><p className="modalintro">Pris, restmengde og produktdetaljer kan endres når som helst.</p><label>Merke<input value={editForm.brand} onChange={e=>setEditForm({...editForm,brand:e.target.value})}/></label><div className="formrow"><label>Flaskestørrelse, ml<input type="number" min="1" value={editForm.bottle_size_ml} onChange={e=>setEditForm({...editForm,bottle_size_ml:e.target.value})}/></label><label>Igjen, ml<input type="number" min="0" value={editForm.remaining_ml} onChange={e=>setEditForm({...editForm,remaining_ml:e.target.value})}/></label></div><div className="formrow"><label>Pris, kr<input type="number" min="0" step="0.01" value={editForm.purchase_price} onChange={e=>setEditForm({...editForm,purchase_price:e.target.value})}/></label><label>ABV, %<input type="number" min="0" max="100" step="0.1" value={editForm.abv} onChange={e=>setEditForm({...editForm,abv:e.target.value})}/></label></div><label>Strekkode<input value={editForm.barcode} onChange={e=>setEditForm({...editForm,barcode:e.target.value})}/></label><label>Handlegrense, ml<input type="number" min="0" value={editForm.low_at_ml} onChange={e=>setEditForm({...editForm,low_at_ml:e.target.value})}/></label><label className="checklabel"><input type="checkbox" checked={editForm.is_open} onChange={e=>setEditForm({...editForm,is_open:e.target.checked})}/> Flasken er åpnet</label><button className="savebtn">Lagre endringer</button></form></div>}

  {bOpen&&<div className="modalback"><form className="modal" onSubmit={addBottle}><button type="button" className="close" onClick={()=>setBOpen(false)}><X/></button><p className="eyebrow">NY FLASKE</p><h2>Legg til i baren</h2><label>Ingrediens<select value={bf.ingredient} onChange={e=>setBf({...bf,ingredient:e.target.value})} required><option value="">Velg…</option>{ING.map(i=><option key={i}>{i}</option>)}<option value="__other__">Annet…</option></select></label>{bf.ingredient==='__other__'&&<label>Egen ingrediens<input value={custom} onChange={e=>setCustom(e.target.value)} required/></label>}<label>Merke<input value={bf.brand} onChange={e=>setBf({...bf,brand:e.target.value})} placeholder="f.eks. Gordon's"/></label><div className="formrow"><label>Flaske, ml<input type="number" value={bf.bottle_size_ml} onChange={e=>setBf({...bf,bottle_size_ml:e.target.value})}/></label><label>Igjen, ml<input type="number" value={bf.remaining_ml} onChange={e=>setBf({...bf,remaining_ml:e.target.value})}/></label></div><div className="formrow"><label>Pris, kr<input type="number" value={bf.purchase_price} onChange={e=>setBf({...bf,purchase_price:e.target.value})}/></label><label>ABV, %<input type="number" step="0.1" value={bf.abv} onChange={e=>setBf({...bf,abv:e.target.value})}/></label></div><label>Strekkode<input value={bf.barcode} onChange={e=>setBf({...bf,barcode:e.target.value})}/></label><label className="checklabel"><input type="checkbox" checked={bf.is_open} onChange={e=>setBf({...bf,is_open:e.target.checked})}/> Flasken er åpnet</label><label>Handlegrense, ml<input type="number" value={bf.low_at_ml} onChange={e=>setBf({...bf,low_at_ml:e.target.value})}/></label><p className="formhint">Har du to like flasker, registrerer du begge. MoBar grupperer dem visuelt, men holder restmengden separat.</p><button className="savebtn">Lagre flaske</button></form></div>}

  {cOpen&&<div className="modalback"><form className="modal wide" onSubmit={addOwn}><button type="button" className="close" onClick={()=>setCOpen(false)}><X/></button><p className="eyebrow">EGEN OPPSKRIFT</p><h2>Ny cocktail</h2><label>Navn<input value={cn} onChange={e=>setCn(e.target.value)} required/></label><label>Beskrivelse<input value={cd} onChange={e=>setCd(e.target.value)}/></label><div className="formrow"><label>Glass<input value={cglass} onChange={e=>setCglass(e.target.value)}/></label><label>Garnityr<input value={cg} onChange={e=>setCg(e.target.value)}/></label></div><label>Fremgangsmåte<textarea value={ci} onChange={e=>setCi(e.target.value)}/></label>{recipe.map((x,i)=><div className="reciperow" key={i}><select value={x.ingredient} onChange={e=>setRecipe(v=>v.map((r,n)=>n===i?{...r,ingredient:e.target.value}:r))}><option value="">Ingrediens…</option>{[...new Set([...bottles.map(x=>x.ingredient),...ING])].sort().map(v=><option key={v}>{v}</option>)}</select><input type="number" value={x.amount_ml} onChange={e=>setRecipe(v=>v.map((r,n)=>n===i?{...r,amount_ml:+e.target.value}:r))}/><button type="button" className="iconbtn" onClick={()=>setRecipe(v=>v.filter((_,n)=>n!==i))}><X/></button></div>)}<button type="button" className="secondary" onClick={()=>setRecipe(v=>[...v,{ingredient:'',amount_ml:20}])}><Plus/>Ingrediens</button><button className="savebtn">Lagre cocktail</button></form></div>}
 </main>
}
