'use client'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {AlertTriangle,Check,FlaskConical,GlassWater,LogOut,Minus,Plus,Search,ShoppingCart,Trash2,Wine,X} from 'lucide-react'
import {supabase} from '@/lib/supabase'
type BottleRow={id:string;ingredient:string;brand:string|null;bottle_size_ml:number;remaining_ml:number;low_at_ml:number}
type RecipeIngredient={ingredient:string;amount_ml:number}
type Cocktail={id:string;name:string;description:string|null;ingredients:RecipeIngredient[]}
const COMMON_INGREDIENTS=['Vodka','Gin','White rum','Dark rum','Spiced rum','Tequila','Bourbon','Whiskey','Scotch','Brandy','Cognac','Triple sec','Cointreau','Grand Marnier','Vermouth sweet','Vermouth dry','Campari','Aperol','Amaretto','Kahlúa','Baileys','Malibu','Jägermeister','Angostura bitters','Lemon juice','Lime juice','Orange juice','Pineapple juice','Cranberry juice','Grapefruit juice','Tomato juice','Sugar syrup','Grenadine','Cola','Soda water','Tonic water','Ginger beer','Ginger ale','Cream','Milk','Coffee','Espresso','Mint','Egg white']
const blankBottle={ingredient:'',brand:'',bottle_size_ml:'700',remaining_ml:'700',low_at_ml:'150'}
export default function Home(){
 const [bottles,setBottles]=useState<BottleRow[]>([]),[cocktails,setCocktails]=useState<Cocktail[]>([]),[tab,setTab]=useState<'drinks'|'bar'|'shopping'>('drinks'),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true)
 const [showBottle,setShowBottle]=useState(false),[showCocktail,setShowCocktail]=useState(false),[bottleForm,setBottleForm]=useState(blankBottle),[customBottleIngredient,setCustomBottleIngredient]=useState('')
 const [cocktailName,setCocktailName]=useState(''),[cocktailDescription,setCocktailDescription]=useState(''),[recipe,setRecipe]=useState<RecipeIngredient[]>([{ingredient:'',amount_ml:40}]),[customRecipe,setCustomRecipe]=useState<Record<number,string>>({})
 async function load(){const [{data:b},{data:c}]=await Promise.all([supabase.from('bar_bottles').select('*').order('ingredient'),supabase.from('bar_cocktails').select('id,name,description,bar_recipe_ingredients(ingredient,amount_ml)').order('name')]);setBottles((b||[]) as BottleRow[]);setCocktails((c||[]).map((x:any)=>({id:x.id,name:x.name,description:x.description,ingredients:x.bar_recipe_ingredients||[]})));setLoading(false)}
 useEffect(()=>{load()},[])
 const ingredientOptions=useMemo(()=>Array.from(new Set([...bottles.map(b=>b.ingredient),...COMMON_INGREDIENTS])).sort((a,b)=>a.localeCompare(b)),[bottles])
 const totals=useMemo(()=>{const m:Record<string,number>={};for(const b of bottles)m[b.ingredient]=(m[b.ingredient]||0)+Number(b.remaining_ml);return m},[bottles])
 const canMake=(c:Cocktail)=>c.ingredients.every(i=>(totals[i.ingredient]||0)>=i.amount_ml),filtered=cocktails.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())),low=bottles.filter(b=>+b.remaining_ml<=+b.low_at_ml)
 function flash(text:string){setNotice(text);setTimeout(()=>setNotice(''),2800)}
 async function makeDrink(c:Cocktail){const {error}=await supabase.rpc('make_cocktail',{p_cocktail_id:c.id});if(error){flash(error.message);return}await load();flash(`${c.name} registrert. Lageret er oppdatert.`)}
 async function changeBottle(b:BottleRow,delta:number){const value=Math.max(0,Math.min(+b.bottle_size_ml,+b.remaining_ml+delta));const {error}=await supabase.from('bar_bottles').update({remaining_ml:value}).eq('id',b.id);if(error){flash(error.message);return}setBottles(x=>x.map(v=>v.id===b.id?{...v,remaining_ml:value}:v))}
 async function addBottle(e:FormEvent){e.preventDefault();const ingredient=bottleForm.ingredient==='__custom__'?customBottleIngredient.trim():bottleForm.ingredient.trim();const size=Number(bottleForm.bottle_size_ml),remaining=Number(bottleForm.remaining_ml),lowAt=Number(bottleForm.low_at_ml);if(!ingredient||size<=0||remaining<0||remaining>size){flash('Sjekk ingrediens og mengder.');return}const {error}=await supabase.from('bar_bottles').insert({ingredient,brand:bottleForm.brand.trim()||null,bottle_size_ml:size,remaining_ml:remaining,low_at_ml:Math.max(0,lowAt)});if(error){flash(error.message);return}setBottleForm(blankBottle);setCustomBottleIngredient('');setShowBottle(false);await load();flash('Flasken er lagt til i baren.')}
 async function deleteBottle(id:string){const {error}=await supabase.from('bar_bottles').delete().eq('id',id);if(error){flash(error.message);return}await load();flash('Flasken er fjernet.')}
 async function addCocktail(e:FormEvent){e.preventDefault();const clean=recipe.map((r,i)=>({ingredient:r.ingredient==='__custom__'?(customRecipe[i]||'').trim():r.ingredient.trim(),amount_ml:Number(r.amount_ml)})).filter(r=>r.ingredient&&r.amount_ml>0);if(!cocktailName.trim()||!clean.length){flash('Cocktailen må ha navn og minst én ingrediens.');return}const {data,error}=await supabase.from('bar_cocktails').insert({name:cocktailName.trim(),description:cocktailDescription.trim()||null}).select('id').single();if(error||!data){flash(error?.message||'Kunne ikke lagre cocktailen.');return}const {error:ingredientError}=await supabase.from('bar_recipe_ingredients').insert(clean.map(r=>({...r,cocktail_id:data.id})));if(ingredientError){await supabase.from('bar_cocktails').delete().eq('id',data.id);flash(ingredientError.message);return}setCocktailName('');setCocktailDescription('');setRecipe([{ingredient:'',amount_ml:40}]);setCustomRecipe({});setShowCocktail(false);await load();flash('Cocktailen er lagret.')}
 async function deleteCocktail(id:string){const {error}=await supabase.from('bar_cocktails').delete().eq('id',id);if(error){flash(error.message);return}await load();flash('Cocktailen er slettet.')}
 function removeRecipeRow(index:number){setRecipe(x=>x.filter((_,n)=>n!==index));setCustomRecipe(prev=>{const next:Record<number,string>={};Object.entries(prev).forEach(([k,v])=>{const n=Number(k);if(n<index)next[n]=v;else if(n>index)next[n-1]=v});return next})}
 return <main><header><div className="brand"><div className="logo"><Wine size={25}/></div><div><b>MoBar</b><small>cocktails & inventory</small></div></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut/>Logg ut</button></header><nav><button className={tab==='drinks'?'active':''} onClick={()=>setTab('drinks')}><GlassWater/>Drinker</button><button className={tab==='bar'?'active':''} onClick={()=>setTab('bar')}><FlaskConical/>Min bar</button><button className={tab==='shopping'?'active':''} onClick={()=>setTab('shopping')}><ShoppingCart/>Handleliste{low.length>0&&<i>{low.length}</i>}</button></nav><section className="hero"><p>DIN HJEMMEBAR</p><h1>Hva skal vi lage?</h1><span>Oppskrifter som faktisk vet hvor mye som er igjen i flaskene.</span></section>{notice&&<div className="notice"><Check size={18}/>{notice}</div>}
 {tab==='drinks'&&<section className="content"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Søk etter cocktail..."/></div><div className="sectionTitle"><h2>Cocktails</h2><div className="titleactions"><span>{filtered.filter(canMake).length} kan lages nå</span><button className="addbtn" onClick={()=>setShowCocktail(true)}><Plus/>Ny cocktail</button></div></div>{loading?<div className="empty"><p>Henter oppskrifter…</p></div>:cocktails.length===0?<div className="empty"><GlassWater/><h3>Ingen cocktails ennå</h3><p>Legg inn din første oppskrift med knappen over.</p></div>:<div className="grid">{filtered.map(c=><article className="card" key={c.id}><div className="drinkIcon"><GlassWater/></div><div className="cardbody"><div className="cardtop"><h3>{c.name}</h3><div className="cardactions"><span className={canMake(c)?'ready':'missing'}>{canMake(c)?'KAN LAGES':'MANGLER'}</span><button className="iconbtn" title="Slett cocktail" onClick={()=>deleteCocktail(c.id)}><Trash2/></button></div></div><p>{c.description}</p><div className="ingredients">{c.ingredients.map((i,n)=><span key={`${i.ingredient}-${n}`} className={(totals[i.ingredient]||0)<i.amount_ml?'bad':''}>{i.ingredient} <b>{i.amount_ml} ml</b></span>)}</div><button className="make" disabled={!canMake(c)} onClick={()=>makeDrink(c)}>Lag drinken <span>− trekk fra lager</span></button></div></article>)}</div>}</section>}
 {tab==='bar'&&<section className="content"><div className="sectionTitle"><div><p className="eyebrow">BEHOLDNING</p><h2>Min bar</h2></div><div className="titleactions"><span>{bottles.length} flasker</span><button className="addbtn" onClick={()=>setShowBottle(true)}><Plus/>Ny flaske</button></div></div>{bottles.length===0?<div className="empty"><FlaskConical/><h3>Ingen flasker registrert</h3><p>Legg inn hva du faktisk har i skapet.</p></div>:<div className="bottlegrid">{bottles.map(b=>{const pct=Math.max(0,Math.round(+b.remaining_ml/+b.bottle_size_ml*100));return <article className="bottle" key={b.id}><div className="bottlehead"><FlaskConical/><div><h3>{b.brand||b.ingredient}</h3><p>{b.brand?b.ingredient:'Ingrediens'}</p></div>{+b.remaining_ml<=+b.low_at_ml&&<AlertTriangle className="warn"/>}<button className="iconbtn" title="Fjern flaske" onClick={()=>deleteBottle(b.id)}><Trash2/></button></div><div className="meter"><i style={{width:`${pct}%`}}/></div><div className="amount"><strong>{Math.round(+b.remaining_ml)} ml</strong><span>av {b.bottle_size_ml} ml · {pct}%</span></div><div className="quick"><button onClick={()=>changeBottle(b,-10)}><Minus/>10 ml</button><button onClick={()=>changeBottle(b,10)}><Plus/>10 ml</button></div></article>})}</div>}</section>}
 {tab==='shopping'&&<section className="content"><div className="sectionTitle"><div><p className="eyebrow">PÅFYLL</p><h2>Handleliste</h2></div><span>{low.length} varer</span></div>{low.length===0?<div className="empty"><Check/><h3>Baren er godt fylt</h3><p>Ingenting er under lavgrensen.</p></div>:<div className="shopping">{low.map(b=><div key={b.id}><AlertTriangle/><div><h3>{b.brand||b.ingredient}</h3><p>{Math.round(+b.remaining_ml)} ml igjen · grense {b.low_at_ml} ml</p></div><strong>KJØP</strong></div>)}</div>}</section>}
 {showBottle&&<div className="modalback" onMouseDown={()=>setShowBottle(false)}><form className="modal" onMouseDown={e=>e.stopPropagation()} onSubmit={addBottle}><button type="button" className="close" onClick={()=>setShowBottle(false)}><X/></button><p className="eyebrow">MIN BAR</p><h2>Legg til flaske</h2><label>Ingrediens<select required value={bottleForm.ingredient} onChange={e=>setBottleForm({...bottleForm,ingredient:e.target.value})}><option value="">Velg ingrediens …</option>{COMMON_INGREDIENTS.map(i=><option key={i} value={i}>{i}</option>)}<option value="__custom__">Annet …</option></select></label>{bottleForm.ingredient==='__custom__'&&<label>Egen ingrediens<input required autoFocus placeholder="Skriv ingrediens" value={customBottleIngredient} onChange={e=>setCustomBottleIngredient(e.target.value)}/></label>}<label>Merke<input placeholder="f.eks. Gordon's" value={bottleForm.brand} onChange={e=>setBottleForm({...bottleForm,brand:e.target.value})}/></label><div className="formrow"><label>Flaske, ml<input type="number" min="1" required value={bottleForm.bottle_size_ml} onChange={e=>setBottleForm({...bottleForm,bottle_size_ml:e.target.value})}/></label><label>Igjen, ml<input type="number" min="0" required value={bottleForm.remaining_ml} onChange={e=>setBottleForm({...bottleForm,remaining_ml:e.target.value})}/></label></div><label>Legg på handleliste under, ml<input type="number" min="0" value={bottleForm.low_at_ml} onChange={e=>setBottleForm({...bottleForm,low_at_ml:e.target.value})}/></label><button className="savebtn">Lagre flaske</button></form></div>}
 {showCocktail&&<div className="modalback" onMouseDown={()=>setShowCocktail(false)}><form className="modal wide" onMouseDown={e=>e.stopPropagation()} onSubmit={addCocktail}><button type="button" className="close" onClick={()=>setShowCocktail(false)}><X/></button><p className="eyebrow">OPPSKRIFT</p><h2>Ny cocktail</h2><label>Navn<input required placeholder="f.eks. Long Island Iced Tea" value={cocktailName} onChange={e=>setCocktailName(e.target.value)}/></label><label>Beskrivelse<input placeholder="Kort beskrivelse" value={cocktailDescription} onChange={e=>setCocktailDescription(e.target.value)}/></label><div className="recipehead">Ingredienser</div>{recipe.map((r,i)=><div className="recipeblock" key={i}><div className="reciperow"><select required value={r.ingredient} onChange={e=>setRecipe(x=>x.map((v,n)=>n===i?{...v,ingredient:e.target.value}:v))}><option value="">Velg ingrediens …</option>{ingredientOptions.map(ing=><option key={ing} value={ing}>{bottles.some(b=>b.ingredient===ing)?`★ ${ing}`:ing}</option>)}<option value="__custom__">Annet …</option></select><input required type="number" min="1" placeholder="ml" value={r.amount_ml} onChange={e=>setRecipe(x=>x.map((v,n)=>n===i?{...v,amount_ml:Number(e.target.value)}:v))}/><button type="button" className="iconbtn" onClick={()=>removeRecipeRow(i)}><X/></button></div>{r.ingredient==='__custom__'&&<input className="customingredient" required placeholder="Skriv egen ingrediens" value={customRecipe[i]||''} onChange={e=>setCustomRecipe(x=>({...x,[i]:e.target.value}))}/>}</div>)}<div className="selecthint">★ = finnes i baren din</div><button type="button" className="secondary" onClick={()=>setRecipe(x=>[...x,{ingredient:'',amount_ml:20}])}><Plus/>Legg til ingrediens</button><button className="savebtn">Lagre cocktail</button></form></div>}
 <footer>MoBar · Supabase inventory</footer></main>
}
