'use client'
import {useEffect,useMemo,useState} from 'react'
import {AlertTriangle,Check,FlaskConical,GlassWater,LogOut,Minus,Plus,Search,ShoppingCart,Wine} from 'lucide-react'
import {supabase} from '@/lib/supabase'
type BottleRow={id:string;ingredient:string;brand:string|null;bottle_size_ml:number;remaining_ml:number;low_at_ml:number}
type RecipeIngredient={ingredient:string;amount_ml:number}
type Cocktail={id:string;name:string;description:string|null;ingredients:RecipeIngredient[]}
export default function Home(){
 const [bottles,setBottles]=useState<BottleRow[]>([]),[cocktails,setCocktails]=useState<Cocktail[]>([]),[tab,setTab]=useState<'drinks'|'bar'|'shopping'>('drinks'),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true)
 async function load(){const [{data:b},{data:c}]=await Promise.all([supabase.from('bar_bottles').select('*').order('ingredient'),supabase.from('bar_cocktails').select('id,name,description,bar_recipe_ingredients(ingredient,amount_ml)').order('name')]);setBottles((b||[]) as BottleRow[]);setCocktails((c||[]).map((x:any)=>({id:x.id,name:x.name,description:x.description,ingredients:x.bar_recipe_ingredients||[]})));setLoading(false)}
 useEffect(()=>{load()},[])
 const totals=useMemo(()=>{const m:Record<string,number>={};for(const b of bottles)m[b.ingredient]=(m[b.ingredient]||0)+Number(b.remaining_ml);return m},[bottles])
 const canMake=(c:Cocktail)=>c.ingredients.every(i=>(totals[i.ingredient]||0)>=i.amount_ml),filtered=cocktails.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())),low=bottles.filter(b=>+b.remaining_ml<=+b.low_at_ml)
 async function makeDrink(c:Cocktail){const {error}=await supabase.rpc('make_cocktail',{p_cocktail_id:c.id});if(error){setNotice(error.message);return}await load();setNotice(`${c.name} registrert. Lageret er oppdatert.`);setTimeout(()=>setNotice(''),2500)}
 async function changeBottle(b:BottleRow,delta:number){const value=Math.max(0,Math.min(+b.bottle_size_ml,+b.remaining_ml+delta));await supabase.from('bar_bottles').update({remaining_ml:value}).eq('id',b.id);setBottles(x=>x.map(v=>v.id===b.id?{...v,remaining_ml:value}:v))}
 return <main><header><div className="brand"><div className="logo"><Wine size={25}/></div><div><b>MoBar</b><small>cocktails & inventory</small></div></div><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut/>Logg ut</button></header><nav><button className={tab==='drinks'?'active':''} onClick={()=>setTab('drinks')}><GlassWater/>Drinker</button><button className={tab==='bar'?'active':''} onClick={()=>setTab('bar')}><FlaskConical/>Min bar</button><button className={tab==='shopping'?'active':''} onClick={()=>setTab('shopping')}><ShoppingCart/>Handleliste{low.length>0&&<i>{low.length}</i>}</button></nav><section className="hero"><p>DIN HJEMMEBAR</p><h1>Hva skal vi lage?</h1><span>Oppskrifter som faktisk vet hvor mye som er igjen i flaskene.</span></section>{notice&&<div className="notice"><Check size={18}/>{notice}</div>}
 {tab==='drinks'&&<section className="content"><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Søk etter cocktail..."/></div><div className="sectionTitle"><h2>Cocktails</h2><span>{filtered.filter(canMake).length} kan lages nå</span></div>{loading?<div className="empty"><p>Henter oppskrifter…</p></div>:cocktails.length===0?<div className="empty"><GlassWater/><h3>Ingen cocktails ennå</h3><p>Databasen er klar. Neste steg er å importere oppskrifter.</p></div>:<div className="grid">{filtered.map(c=><article className="card" key={c.id}><div className="drinkIcon"><GlassWater/></div><div className="cardbody"><div className="cardtop"><h3>{c.name}</h3><span className={canMake(c)?'ready':'missing'}>{canMake(c)?'KAN LAGES':'MANGLER'}</span></div><p>{c.description}</p><div className="ingredients">{c.ingredients.map(i=><span key={i.ingredient} className={(totals[i.ingredient]||0)<i.amount_ml?'bad':''}>{i.ingredient} <b>{i.amount_ml} ml</b></span>)}</div><button className="make" disabled={!canMake(c)} onClick={()=>makeDrink(c)}>Lag drinken <span>− trekk fra lager</span></button></div></article>)}</div>}</section>}
 {tab==='bar'&&<section className="content"><div className="sectionTitle"><div><p className="eyebrow">BEHOLDNING</p><h2>Min bar</h2></div><span>{bottles.length} flasker</span></div>{bottles.length===0?<div className="empty"><FlaskConical/><h3>Ingen flasker registrert</h3><p>Lageret er tomt foreløpig.</p></div>:<div className="bottlegrid">{bottles.map(b=>{const pct=Math.max(0,Math.round(+b.remaining_ml/+b.bottle_size_ml*100));return <article className="bottle" key={b.id}><div className="bottlehead"><FlaskConical/><div><h3>{b.brand||b.ingredient}</h3><p>{b.brand?b.ingredient:'Ingrediens'}</p></div>{+b.remaining_ml<=+b.low_at_ml&&<AlertTriangle className="warn"/>}</div><div className="meter"><i style={{width:`${pct}%`}}/></div><div className="amount"><strong>{Math.round(+b.remaining_ml)} ml</strong><span>av {b.bottle_size_ml} ml · {pct}%</span></div><div className="quick"><button onClick={()=>changeBottle(b,-10)}><Minus/>10 ml</button><button onClick={()=>changeBottle(b,10)}><Plus/>10 ml</button></div></article>})}</div>}</section>}
 {tab==='shopping'&&<section className="content"><div className="sectionTitle"><div><p className="eyebrow">PÅFYLL</p><h2>Handleliste</h2></div><span>{low.length} varer</span></div>{low.length===0?<div className="empty"><Check/><h3>Baren er godt fylt</h3><p>Ingenting er under lavgrensen.</p></div>:<div className="shopping">{low.map(b=><div key={b.id}><AlertTriangle/><div><h3>{b.brand||b.ingredient}</h3><p>{Math.round(+b.remaining_ml)} ml igjen · grense {b.low_at_ml} ml</p></div><strong>KJØP</strong></div>)}</div>}</section>}<footer>MoBar · Supabase inventory</footer></main>
}
