export type CatalogCocktail={
  name:string
  description:string
  ingredients:{ingredient:string;amount_ml:number}[]
  glass?:string
  garnish?:string
  instructions?:string
  tags?:string[]
}

export const COCKTAIL_CATALOG:CatalogCocktail[]=[
{name:'Long Island Iced Tea',description:'Vodka, gin, rom, tequila, triple sec, sitrus og cola.',glass:'Highball',garnish:'Sitron',tags:['strong','classic','long'],instructions:'Bygg over is, rør kort og topp med cola.',ingredients:[{ingredient:'Vodka',amount_ml:15},{ingredient:'Gin',amount_ml:15},{ingredient:'White rum',amount_ml:15},{ingredient:'Tequila',amount_ml:15},{ingredient:'Triple sec',amount_ml:15},{ingredient:'Lemon juice',amount_ml:25},{ingredient:'Sugar syrup',amount_ml:15},{ingredient:'Cola',amount_ml:60}]},
{name:'Mojito',description:'Rom, lime, mynte, sukker og soda.',glass:'Highball',garnish:'Mynte og lime',tags:['refreshing','classic','long'],instructions:'Bygg i glass med is. Rør og topp med soda.',ingredients:[{ingredient:'White rum',amount_ml:50},{ingredient:'Lime juice',amount_ml:25},{ingredient:'Sugar syrup',amount_ml:15},{ingredient:'Mint',amount_ml:10},{ingredient:'Soda water',amount_ml:60}]},
{name:'Daiquiri',description:'Klassisk romdrink med lime og sukker.',glass:'Coupe',garnish:'Lime',tags:['sour','classic','short'],instructions:'Shake med is og sil i avkjølt glass.',ingredients:[{ingredient:'White rum',amount_ml:60},{ingredient:'Lime juice',amount_ml:30},{ingredient:'Sugar syrup',amount_ml:20}]},
{name:'Tom Collins',description:'Gin, sitron, sukker og soda.',glass:'Highball',garnish:'Sitron',tags:['refreshing','sour','long'],instructions:'Shake alt unntatt soda. Sil over is og topp med soda.',ingredients:[{ingredient:'Gin',amount_ml:50},{ingredient:'Lemon juice',amount_ml:25},{ingredient:'Sugar syrup',amount_ml:15},{ingredient:'Soda water',amount_ml:60}]},
{name:'Gin & Tonic',description:'Gin og tonic, enkelt fordi enkelte ting faktisk får lov til å være det.',glass:'Highball',garnish:'Lime',tags:['easy','refreshing','long'],instructions:'Bygg over mye is og rør forsiktig.',ingredients:[{ingredient:'Gin',amount_ml:50},{ingredient:'Tonic water',amount_ml:120}]},
{name:'Margarita',description:'Tequila, appelsinlikør og lime.',glass:'Coupe',garnish:'Saltkant og lime',tags:['sour','classic','short'],instructions:'Shake med is og sil i glass.',ingredients:[{ingredient:'Tequila',amount_ml:50},{ingredient:'Triple sec',amount_ml:25},{ingredient:'Lime juice',amount_ml:25}]},
{name:'Espresso Martini',description:'Vodka, kaffelikør og espresso.',glass:'Coupe',garnish:'Kaffebønner',tags:['coffee','sweet','modern'],instructions:'Shake hardt med is og finsil.',ingredients:[{ingredient:'Vodka',amount_ml:40},{ingredient:'Kahlúa',amount_ml:20},{ingredient:'Espresso',amount_ml:30},{ingredient:'Sugar syrup',amount_ml:10}]},
{name:'Whiskey Sour',description:'Whiskey, sitron og sukker.',glass:'Rocks',garnish:'Sitron',tags:['sour','classic','short'],instructions:'Shake med is og sil over fersk is.',ingredients:[{ingredient:'Whiskey',amount_ml:60},{ingredient:'Lemon juice',amount_ml:30},{ingredient:'Sugar syrup',amount_ml:20}]},
{name:'Old Fashioned',description:'Whiskey, sukker og bitters.',glass:'Rocks',garnish:'Appelsinskall',tags:['strong','classic','short'],instructions:'Rør med is og server over stor isbit.',ingredients:[{ingredient:'Whiskey',amount_ml:60},{ingredient:'Sugar syrup',amount_ml:10},{ingredient:'Angostura bitters',amount_ml:2}]},
{name:'Negroni',description:'Gin, Campari og søt vermut.',glass:'Rocks',garnish:'Appelsinskall',tags:['strong','bitter','classic'],instructions:'Rør med is og sil over fersk is.',ingredients:[{ingredient:'Gin',amount_ml:30},{ingredient:'Campari',amount_ml:30},{ingredient:'Vermouth sweet',amount_ml:30}]},
{name:'Aperol Spritz',description:'Aperol, prosecco og soda.',glass:'Wine',garnish:'Appelsin',tags:['refreshing','bitter','long'],instructions:'Bygg over is og rør forsiktig.',ingredients:[{ingredient:'Aperol',amount_ml:60},{ingredient:'Prosecco',amount_ml:90},{ingredient:'Soda water',amount_ml:30}]},
{name:'Moscow Mule',description:'Vodka, lime og ginger beer.',glass:'Mug',garnish:'Lime',tags:['refreshing','spicy','long'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'Vodka',amount_ml:50},{ingredient:'Lime juice',amount_ml:20},{ingredient:'Ginger beer',amount_ml:120}]},
{name:'Cuba Libre',description:'Rom, cola og lime.',glass:'Highball',garnish:'Lime',tags:['easy','long'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'White rum',amount_ml:50},{ingredient:'Cola',amount_ml:120},{ingredient:'Lime juice',amount_ml:15}]},
{name:'Tequila Sunrise',description:'Tequila, appelsin og grenadine.',glass:'Highball',garnish:'Appelsin',tags:['sweet','fruity','long'],instructions:'Bygg tequila og juice over is. Hell grenadine forsiktig i.',ingredients:[{ingredient:'Tequila',amount_ml:50},{ingredient:'Orange juice',amount_ml:100},{ingredient:'Grenadine',amount_ml:15}]},
{name:'Piña Colada',description:'Rom, ananas og kokos.',glass:'Hurricane',garnish:'Ananas',tags:['sweet','fruity','tropical'],instructions:'Shake eller blend med is.',ingredients:[{ingredient:'White rum',amount_ml:50},{ingredient:'Pineapple juice',amount_ml:90},{ingredient:'Coconut cream',amount_ml:30}]},
{name:'Sex on the Beach',description:'Vodka, ferskenlikør, appelsin og tranebær.',glass:'Highball',garnish:'Appelsin',tags:['sweet','fruity','long'],instructions:'Bygg eller shake og server over is.',ingredients:[{ingredient:'Vodka',amount_ml:40},{ingredient:'Peach schnapps',amount_ml:20},{ingredient:'Orange juice',amount_ml:50},{ingredient:'Cranberry juice',amount_ml:50}]},
{name:'White Russian',description:'Vodka, kaffelikør og fløte.',glass:'Rocks',tags:['sweet','coffee','dessert'],instructions:'Bygg over is og legg fløte på toppen.',ingredients:[{ingredient:'Vodka',amount_ml:50},{ingredient:'Kahlúa',amount_ml:25},{ingredient:'Cream',amount_ml:25}]},
{name:'Black Russian',description:'Vodka og kaffelikør.',glass:'Rocks',tags:['easy','coffee','strong'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'Vodka',amount_ml:50},{ingredient:'Kahlúa',amount_ml:25}]},
{name:'Amaretto Sour',description:'Amaretto, sitron og sukker.',glass:'Rocks',garnish:'Sitron',tags:['sweet','sour'],instructions:'Shake med is og sil over fersk is.',ingredients:[{ingredient:'Amaretto',amount_ml:50},{ingredient:'Lemon juice',amount_ml:30},{ingredient:'Sugar syrup',amount_ml:15}]},
{name:'Dark ’n’ Stormy',description:'Mørk rom, lime og ginger beer.',glass:'Highball',garnish:'Lime',tags:['spicy','refreshing','long'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'Dark rum',amount_ml:50},{ingredient:'Lime juice',amount_ml:20},{ingredient:'Ginger beer',amount_ml:120}]},
{name:'Mai Tai',description:'Rom, appelsinlikør, lime og mandel.',glass:'Rocks',garnish:'Lime og mynte',tags:['tropical','strong','classic'],instructions:'Shake med is og hell over knust is.',ingredients:[{ingredient:'White rum',amount_ml:30},{ingredient:'Dark rum',amount_ml:30},{ingredient:'Triple sec',amount_ml:15},{ingredient:'Lime juice',amount_ml:25},{ingredient:'Sugar syrup',amount_ml:10}]},
{name:'Cosmopolitan',description:'Vodka, appelsinlikør, lime og tranebær.',glass:'Coupe',garnish:'Appelsinskall',tags:['fruity','sour','modern'],instructions:'Shake med is og sil.',ingredients:[{ingredient:'Vodka',amount_ml:40},{ingredient:'Triple sec',amount_ml:20},{ingredient:'Lime juice',amount_ml:15},{ingredient:'Cranberry juice',amount_ml:30}]},
{name:'French 75',description:'Gin, sitron, sukker og prosecco.',glass:'Flute',garnish:'Sitron',tags:['refreshing','sparkling','classic'],instructions:'Shake gin, sitron og sukker. Sil og topp med prosecco.',ingredients:[{ingredient:'Gin',amount_ml:30},{ingredient:'Lemon juice',amount_ml:15},{ingredient:'Sugar syrup',amount_ml:10},{ingredient:'Prosecco',amount_ml:60}]},
{name:'Manhattan',description:'Whiskey, søt vermut og bitters.',glass:'Coupe',garnish:'Kirsebær',tags:['strong','classic','short'],instructions:'Rør med is og sil.',ingredients:[{ingredient:'Whiskey',amount_ml:60},{ingredient:'Vermouth sweet',amount_ml:30},{ingredient:'Angostura bitters',amount_ml:2}]},
{name:'Dry Martini',description:'Gin og tørr vermut.',glass:'Martini',garnish:'Oliven eller sitronskall',tags:['strong','classic','short'],instructions:'Rør kaldt med is og sil.',ingredients:[{ingredient:'Gin',amount_ml:60},{ingredient:'Vermouth dry',amount_ml:10}]},
{name:'Vodka Martini',description:'Vodka og tørr vermut.',glass:'Martini',garnish:'Oliven eller sitronskall',tags:['strong','classic','short'],instructions:'Rør eller shake med is og sil.',ingredients:[{ingredient:'Vodka',amount_ml:60},{ingredient:'Vermouth dry',amount_ml:10}]},
{name:'Gimlet',description:'Gin, lime og sukker.',glass:'Coupe',garnish:'Lime',tags:['sour','classic','easy'],instructions:'Shake med is og sil.',ingredients:[{ingredient:'Gin',amount_ml:60},{ingredient:'Lime juice',amount_ml:25},{ingredient:'Sugar syrup',amount_ml:15}]},
{name:'Paloma',description:'Tequila og grapefrukt med frisk syre.',glass:'Highball',garnish:'Grapefrukt',tags:['refreshing','fruity','long'],instructions:'Bygg over is og topp med soda.',ingredients:[{ingredient:'Tequila',amount_ml:50},{ingredient:'Grapefruit juice',amount_ml:80},{ingredient:'Lime juice',amount_ml:15},{ingredient:'Soda water',amount_ml:50}]},
{name:'Bloody Mary',description:'Vodka, tomat og sitrus.',glass:'Highball',garnish:'Selleri eller sitron',tags:['savory','brunch','long'],instructions:'Rull eller rør med is.',ingredients:[{ingredient:'Vodka',amount_ml:50},{ingredient:'Tomato juice',amount_ml:100},{ingredient:'Lemon juice',amount_ml:15}]},
{name:'Sea Breeze',description:'Vodka, tranebær og grapefrukt.',glass:'Highball',garnish:'Lime',tags:['fruity','refreshing','easy'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'Vodka',amount_ml:40},{ingredient:'Cranberry juice',amount_ml:80},{ingredient:'Grapefruit juice',amount_ml:40}]},
{name:'Bay Breeze',description:'Vodka, tranebær og ananas.',glass:'Highball',garnish:'Lime',tags:['fruity','sweet','easy'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'Vodka',amount_ml:40},{ingredient:'Cranberry juice',amount_ml:70},{ingredient:'Pineapple juice',amount_ml:70}]},
{name:'Woo Woo',description:'Vodka, ferskenlikør og tranebær.',glass:'Highball',garnish:'Lime',tags:['fruity','sweet','easy'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'Vodka',amount_ml:40},{ingredient:'Peach schnapps',amount_ml:20},{ingredient:'Cranberry juice',amount_ml:100}]},
{name:'Godfather',description:'Whiskey og amaretto.',glass:'Rocks',tags:['strong','easy','sweet'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'Whiskey',amount_ml:50},{ingredient:'Amaretto',amount_ml:25}]},
{name:'Godmother',description:'Vodka og amaretto.',glass:'Rocks',tags:['strong','easy','sweet'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'Vodka',amount_ml:50},{ingredient:'Amaretto',amount_ml:25}]},
{name:'Rusty Nail',description:'Scotch og søt krydret likør.',glass:'Rocks',tags:['strong','classic'],instructions:'Bygg over is og rør.',ingredients:[{ingredient:'Scotch',amount_ml:50},{ingredient:'Amaretto',amount_ml:20}]},
{name:'John Collins',description:'Whiskey, sitron, sukker og soda.',glass:'Highball',garnish:'Sitron',tags:['refreshing','sour','long'],instructions:'Shake base, sil over is og topp med soda.',ingredients:[{ingredient:'Whiskey',amount_ml:50},{ingredient:'Lemon juice',amount_ml:25},{ingredient:'Sugar syrup',amount_ml:15},{ingredient:'Soda water',amount_ml:60}]},
{name:'Rum & Coke',description:'Rom og cola.',glass:'Highball',tags:['easy','long'],instructions:'Bygg over is.',ingredients:[{ingredient:'White rum',amount_ml:50},{ingredient:'Cola',amount_ml:120}]},
{name:'Vodka Tonic',description:'Vodka og tonic.',glass:'Highball',garnish:'Lime',tags:['easy','refreshing','long'],instructions:'Bygg over is.',ingredients:[{ingredient:'Vodka',amount_ml:50},{ingredient:'Tonic water',amount_ml:120}]},
{name:'Gin Fizz',description:'Gin, sitron, sukker og soda.',glass:'Highball',garnish:'Sitron',tags:['refreshing','sour','classic'],instructions:'Shake base og topp med soda.',ingredients:[{ingredient:'Gin',amount_ml:50},{ingredient:'Lemon juice',amount_ml:25},{ingredient:'Sugar syrup',amount_ml:15},{ingredient:'Soda water',amount_ml:60}]},
{name:'Rum Sour',description:'Rom, sitron og sukker.',glass:'Rocks',garnish:'Sitron',tags:['sour','easy'],instructions:'Shake med is og sil over fersk is.',ingredients:[{ingredient:'White rum',amount_ml:60},{ingredient:'Lemon juice',amount_ml:30},{ingredient:'Sugar syrup',amount_ml:20}]},
{name:'Tequila Sour',description:'Tequila, sitron og sukker.',glass:'Rocks',garnish:'Sitron',tags:['sour','easy'],instructions:'Shake med is og sil over fersk is.',ingredients:[{ingredient:'Tequila',amount_ml:60},{ingredient:'Lemon juice',amount_ml:30},{ingredient:'Sugar syrup',amount_ml:20}]},
{name:'Vodka Sour',description:'Vodka, sitron og sukker.',glass:'Rocks',garnish:'Sitron',tags:['sour','easy'],instructions:'Shake med is og sil over fersk is.',ingredients:[{ingredient:'Vodka',amount_ml:60},{ingredient:'Lemon juice',amount_ml:30},{ingredient:'Sugar syrup',amount_ml:20}]},
{name:'Cape Codder',description:'Vodka og tranebær.',glass:'Highball',garnish:'Lime',tags:['easy','fruity','long'],instructions:'Bygg over is.',ingredients:[{ingredient:'Vodka',amount_ml:50},{ingredient:'Cranberry juice',amount_ml:120}]},
{name:'Greyhound',description:'Vodka og grapefrukt.',glass:'Highball',garnish:'Grapefrukt',tags:['easy','fruity','sour'],instructions:'Bygg over is.',ingredients:[{ingredient:'Vodka',amount_ml:50},{ingredient:'Grapefruit juice',amount_ml:120}]},
{name:'Screwdriver',description:'Vodka og appelsinjuice.',glass:'Highball',garnish:'Appelsin',tags:['easy','fruity','long'],instructions:'Bygg over is.',ingredients:[{ingredient:'Vodka',amount_ml:50},{ingredient:'Orange juice',amount_ml:120}]},
{name:'Brandy Alexander',description:'Brandy, kaffelikør og fløte.',glass:'Coupe',tags:['sweet','dessert'],instructions:'Shake med is og sil.',ingredients:[{ingredient:'Brandy',amount_ml:40},{ingredient:'Kahlúa',amount_ml:30},{ingredient:'Cream',amount_ml:30}]},
{name:'Between the Sheets',description:'Brandy, rom, triple sec og sitron.',glass:'Coupe',garnish:'Sitron',tags:['strong','sour','classic'],instructions:'Shake med is og sil.',ingredients:[{ingredient:'Brandy',amount_ml:30},{ingredient:'White rum',amount_ml:30},{ingredient:'Triple sec',amount_ml:30},{ingredient:'Lemon juice',amount_ml:20}]},
{name:'Sidecar',description:'Brandy, triple sec og sitron.',glass:'Coupe',garnish:'Sitron',tags:['sour','classic','strong'],instructions:'Shake med is og sil.',ingredients:[{ingredient:'Brandy',amount_ml:50},{ingredient:'Triple sec',amount_ml:25},{ingredient:'Lemon juice',amount_ml:25}]},
{name:'Kamikaze',description:'Vodka, triple sec og lime.',glass:'Coupe',garnish:'Lime',tags:['sour','strong','easy'],instructions:'Shake med is og sil.',ingredients:[{ingredient:'Vodka',amount_ml:40},{ingredient:'Triple sec',amount_ml:30},{ingredient:'Lime juice',amount_ml:30}]},
{name:'Blue Lagoon',description:'Vodka, appelsinlikør og sitrus.',glass:'Highball',garnish:'Sitron',tags:['sweet','fruity','long'],instructions:'Bygg over is og topp med soda.',ingredients:[{ingredient:'Vodka',amount_ml:40},{ingredient:'Triple sec',amount_ml:20},{ingredient:'Lemon juice',amount_ml:20},{ingredient:'Soda water',amount_ml:80}]}
]
